### ISSUE TITLE
How to disable the "MAVManager::setPositionCommand"

### ISSUE THREAD

**Issue by youngjae41** [yuwei-wu/Fast-Planner#1]
Hello ! 

Thank you for the good content.

I'm trying to implement it using Pixhawk

How to disable the "MAVManager::setPositionCommand"?

thank.

**Comment by yuwei-wu** [comment]
Because it is used with kr_mav_control, I switch to the null tracker so that the mav_service will not send the command at the same time. If you don't use the kr_mav_control, you do not have to worry about this issue.

In addition, there is no Bspline trajectory tracker for the kr_mav_control now, you can implement one for your mav_service use.

**Comment by youngjae41** [comment]
thanks!!
